### ISSUE TITLE
Change team player link

### ISSUE THREAD

**Issue by freke70** [xAranaktu/FIFA-21-Live-Editor#7]
Hi,
I'm trying to alter the teams and adding a new player to it.
I created new female player.
In the database I changed the gender of the new player to male.
I looked in the teamplayerlink database I changed the Team to the ID  want this player to be on.
After saving however, nothing changes.
I tried restarting, sometimes I see the changes were undone, but sometimes the changes stick, but the player is still not visible in the Team.

The odd thing is, I got it working at one point, but after restarting the game my changes were undone. I have no idea how I got it working.

If you have any tips, or if I should ask questions somewhere else, please let me know.

Thanks for making this wonderful tool!

**Comment by xAranaktu** [comment]
I don't know which tables you exactly need to edit to transfer player manually. Record in teamplayerlink  doesn't seem to be enough. You should probably also edit default_teamsheets, maybe default_mentalities & formations and who knows what else.

However, you can try to make the player free agent (teamid 111592) by editing the record in teamplayerlinks and then transfer him/her to the team you want via in-game interace (Customise -> Edit teams -> Club Transfers)

**Comment by freke70** [comment]
Wonderful, thanks for the tips!
I'll get it working sooner or later :)

**Comment by freke70** [comment]
Hi,
Just wanted to let you know, (and anyone else trying this) you're suggestion worked:

_You can try to make the player free agent (teamid 111592) by editing the record in teamplayerlinks and then transfer him/her to the team you want via in-game interace (Customise -> Edit teams -> Club Transfers)_

It does create 2 players in the database, I needed to select/guess the correct one.
Otherwise, when you transfer the player to the team, you can't move them from the substitution/reserves bench to the main squad.
And you never get picked by the trainer during career mode.

There was also no need to change from male to female, doing this changes the body type to male.

**Comment by xAranaktu** [comment]
One record is related to the women national team and the second is related to created players team. You should cancel one of the records.
