### ISSUE TITLE
Force Transfer/ Force Loan Glitch

### ISSUE THREAD

**Issue by Lbyfrd** [xAranaktu/FIFA-21-Live-Editor#8]
For some reason when you force a transfer on using the editor and/or the cheat table, players do not show up when using the formation editor. For example, I force loaned a few of my young and upcoming players to decent sides so that they would progress better, however, I cannot force them into the other team's lineup. 

Please could you fix this? 

Thank you, keep up the great work.

Lee

**Comment by xAranaktu** [comment]
Fixed in v21.1.2.2
